version: '3.8'
services:
  mongodb:
    image: mongo:latest
    container_name: mongodb-whatsapp-bot
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - mongodb_data:/data/db
    restart: unless-stopped
  whatsapp-bot:
    build: .
    container_name: whatsapp-bot
    ports:
      - "80:80"
    environment:
      - NODE_ENV=production
    volumes:
      - ./session_auth_info:/app/session_auth_info
      - ./debug_media:/app/debug_media
    restart: unless-stopped

volumes:
  mongodb_data: